site_name: "MeshExpert Live!"
site_url: http://www.datamesh.com
site_description: A Mixed-Reality Show Product.
repo_url: https://github.com/michael2008/ME-Live-Doc
copyright: "Copyright (C) 2016-2017 DataMesh Inc."
docs_dir: docs
theme: 'readthedocs'

pages:
    - ['index.md', 'Home']
    - ['release-notes.md', 'Release Notes']
    - ['getting-started.md', 'Getting Started']
    - ['product-specifications.md', 'Product Specifications']
    - ['user-guide.md', 'User Guide']
    - ['developer-guide.md', 'Developer Guide']
    - ['METoolkit-overview.md', 'METoolkit Developer Manual', 'Overview']
    - ['toolkit/toolkit-man-configure-your-project.md', 'METoolkit Developer Manual', 'Config Your Project']
    - ['toolkit/toolkit-man-integrated-METoolkit.md', 'METoolkit Developer Manual', 'Integrate METoolkit']
    - ['toolkit/toolkit-man-write-your-first-app.md', 'METoolkit Developer Manual', 'First App by METookit']
    - ['toolkit/toolkit-man-world-anchor-module.md', 'METoolkit Developer Manual', 'World Anchor Module']
    - ['toolkit/toolkit-man-multi-input-module.md', 'METoolkit Developer Manual', 'Multi-Input Module']
    - ['toolkit/toolkit-man-speech-module.md', 'METoolkit Developer Manual', 'Speech Module']
    - ['toolkit/toolkit-man-ui-module.md', 'METoolkit Developer Manual', 'UI Module']
    - ['toolkit/toolkit-man-collaboration-module.md', 'METoolkit Developer Manual', 'Collaboration Module']
    - ['toolkit/toolkit-man-storage-module.md', 'METoolkit Developer Manual', 'Storage Module']
    - ['toolkit/toolkit-man-live-module.md', 'METoolkit Developer Manual', 'Live Module']
    - ['toolkit/toolkit-man-utility-config-file.md', 'METoolkit Developer Manual', 'Utility: Config Files']
    - ['trouble-shooting.md', 'Trouble Shooting']
    - ['release-history.md', 'Release History']

markdown_extensions:
    - admonition: